### ISSUE TITLE
OAS servers definitions can only be tested in the designer on localhost

### ISSUE THREAD

**Issue by alexwoodgate** [zosconnect/sample-db2-api#5]
The OAS specs have set the servers definition to:
```
servers:
  - url: /project
  - url: http://localhost:9080/
  - url: https://localhost:9443/
  ```
which means the designer's test tool, API explorer will only work if the designer is accessible on local host (as the API is hosted on / so /project doesn't work either).

Updating it to:
```
servers:
- url: /
```
should make the it work in more scenarios, such as CodeReady workspaces where the host name depends on where the workspace.

Only needed in the db2 sample for the root OAS as the start and finish examples are already correct.
